### PR TITLE
Fix username is not updated when the user change their username

### LINKED ISSUE #299: Highlight doesn't update when logged in user is renamed
# Issue
When you teenage yourself on Twitch while logged in DankChat. Highlight will still be effective on your old username.

# Expected behavior
Highlights would work on your new username, and no longer work on you old name.

# Observed behavior
See the screenshot, my current username is `doge41732` (was `rod41732`)
- highlights still work on my old name. (See my message at the bottom-ish)
- highlights doesn't work on my new name. (See supibot's messages)
Screenshot_20220808-191235

### PR DESCRIPTION
**Pull request by rod41732**
This fixes #299.

### CODE REVIEW

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt [hunk 1]
```diff
@@ -1,31 +1,67 @@
...
         if (tryReconnect && started) {
             chatRepository.reconnectIfNecessary()
         } else {
             started = true
-            chatRepository.connectAndJoin(name, oAuth, channels)
+            viewModelScope.launch {
+                val token = oAuth.withoutOAuthSuffix
+
+                var nameToUpdate = name // fallback to old name
+                runCatching {
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:43]: This can be refactored a bit to not have the `var` by using `getOrElse` and moving some of the success logic inside the `runCatching`:
```kotlin
val token = oAuth.withoutOAuthSuffix

val validatedName = runCatching {
    val validationResult = apiManager.validateUser(token)
    if (validationResult== null && token.isNotEmpty()) {
        _validationError.emit(OAuthValidationError.OAuthTokenInvalid)
    }

    validationResult?.login
}.getOrElse {
    // Connection failure
    _validationError.emit(OAuthValidationError.OAuthValidationFailure)
    null
}
val nameToUpdate = validatedName ?: name // fallback to old name
_currentUserName.value = nameToUpdate
dankChatPreferenceStore.userName = nameToUpdate
chatRepository.connectAndJoin(nameToUpdate, oAuth, channels)
```

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt [hunk 2]
```diff
@@ -1,31 +1,67 @@
...
 ) : ViewModel() {
 
     val commands = dataRepository.commands
     var started = false
         private set
 
+    private val _currentUserName = MutableStateFlow<String?>(null)
+    val currentUserName: StateFlow<String?> get() = _currentUserName.asStateFlow()
+
+    private val _validationError = MutableSharedFlow<OAuthValidationError>(extraBufferCapacity = 1, onBufferOverflow = BufferOverflow.DROP_OLDEST)
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:31]: I"ve so far always used a Channel with a unlimited buffer for these types of one-shot events, but have also heard that SharedFlows are also a valid option. Any reason why you chose them here?

File: app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt [hunk 3]
```diff
@@ -403,12 +407,30 @@ class MainFragment : Fragment() {
...
+                            showSnackBar(getString(R.string.snackbar_login, it))
+                        }
                     }
                 }
             }
+            // handle oAuth validation error
+            collectFlow(dankChatViewModel.validationError) {
+                when (it) {
+                    OAuthValidationError.OAuthTokenInvalid      -> {
+                        // I'm too donk to create a Fragment or something sorry
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt:422]: FeelsDankMan fragments would be overkill for a simple error use-case, the DialogBuilder is perfect here
```suggestion
```

File: app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt [hunk 4]
```diff
@@ -403,12 +407,30 @@ class MainFragment : Fragment() {
...
+                        MaterialAlertDialogBuilder(requireContext())
+                            .setTitle(getString(R.string.oauth_expired_title))
+                            .setMessage(getString(R.string.oauth_expired_message))
+                            .setPositiveButton(getString(R.string.oauth_expired_login_again)) { _, _ -> navigateSafe(R.id.action_mainFragment_to_loginFragment) }
+                            .setNegativeButton(getString(R.string.oauth_expired_dismiss)) { _, _ -> } // default action is dismissing anyway
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt:427]: Is `Dismiss` or `Later` a negative button or should we maybe make it a neutral one? Main difference is the button placement in the dialog

**Review by flex3r — CHANGES_REQUESTED** [review]
FeelsDankMan logic itself looks solid, just some UX and Kotlin style changes and we good 👍

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt (hunk 2 above)
Comment (rod41732) [reply app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:31]: I think that the error will likely result in UI changes (like toast, or dialog) if there is too many errors (for whatever reason) there might be a lot of message showing up, so I limit it to be "latest" error only.

File: app/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -314,6 +314,11 @@
     <string name="preference_repeated_sending_key" translatable="false">repeated_sending_key</string>
     <string name="preference_repeated_sending_title">Enable repeated sending</string>
     <string name="preference_repeated_sending_summary">Enables continuous message sending while send button is held</string>
+    <string name="oauth_expired_title">Login Expired!</string>
+    <string name="oauth_expired_message">Your OAuth token is expired! Please login again.</string>
```
[the remark this answers is not in the document]
Comment (rod41732) [reply app/src/main/res/values/strings.xml:318]: Should I call `Login token`? It would be simpler than `Authentication token` IMO.

File: app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt (hunk 4 above)
Comment (rod41732) [reply app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt:427]: I think the `Dismiss` or `Later` button is negative in sense of "Do you want to login again?" -> Yes = Login again, No = Dismiss.

File: app/src/main/res/values/strings.xml (hunk 5 above)
[the remark this answers is not in the document]
Comment (flex3r) [reply app/src/main/res/values/strings.xml:318]: Fine with me 👍

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt (hunk 2 above)
Comment (flex3r) [reply app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:31]: That does make sense, there are conflated channels for this use case as well. Also, I think we can actually merge the username Flow and the validation error one, by having a some kind of `ValidationResult` sealed class that contains a `data class ValidUser(val userName: String)`  and the existing errors. Then we would only have a single collection for all events.

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt [hunk 6]
```diff
@@ -1,31 +1,61 @@
...
             chatRepository.reconnectIfNecessary()
         } else {
             started = true
-            chatRepository.connectAndJoin(name, oAuth, channels)
+            viewModelScope.launch {
+                val token = oAuth.withoutOAuthSuffix
+                val nameToUse = runCatching {
+                    val result = apiManager.validateUser(token)
+                    if (result == null && token.isNotEmpty()) {
+                        _oauthResult.emit(OAuthResult.OAuthTokenInvalid)
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:42]: If the token is invalid we still emit the `OauthResult.UserName` here. I think it would be better to early-return with
```kotlin
return@runCatching null
```

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt [hunk 7]
```diff
@@ -1,31 +1,61 @@
...
+    private val dankChatPreferenceStore: DankChatPreferenceStore,
+    private val apiManager: ApiManager,
     dataRepository: DataRepository,
 ) : ViewModel() {
 
     val commands = dataRepository.commands
     var started = false
         private set
 
+    private val _oauthResult = MutableSharedFlow<OAuthResult>(extraBufferCapacity = 2, onBufferOverflow = BufferOverflow.DROP_OLDEST)
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:29]: I still think we should use a channel here, as a SharedFlow has the downside of dropping elements if there is no subscriber. So in the rare edge-case where the user rotates his phone while we send our result we would not receive the result:
```kotlin
private val _oauthResult = Channel<OAuthResult>(Channel.BUFFERED)
val oAuthResult = _oauthResult.receiveAsFlow()
```
Also, can we rename the sealed class and properties here to maybe `ValidationResult`?

File: app/src/main/kotlin/com/flxrs/dankchat/OAuthResult.kt [hunk 8]
```diff
@@ -0,0 +1,8 @@
+package com.flxrs.dankchat
+
+sealed class OAuthResult {
+    // This is named UserName instead of ValidUser because it's also used in case of fallback
+    data class UserName(val username: String) : OAuthResult()
+    object OAuthTokenInvalid : OAuthResult()
+    object OAuthValidationFailure : OAuthResult()
+}
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/OAuthResult.kt:8]: Some naming updates I would like:
```suggestion
sealed class ValidationResult {
    data class User(val username: String) : ValidationResult()
    object TokenInvalid : ValidationResult()
    object Failure : ValidationResult()
}
```

File: app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt (hunk 7 above)
Comment (rod41732) [reply app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt:29]: OK, I'll rename as you suggested below :+1:

Comment (flex3r) [reply app/src/main/kotlin/com/flxrs/dankchat/DankChatViewModel.kt]: Change it to a `Channel` instead of `SharedFlow` and we're good to go

File: app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt [hunk 9]
```diff
@@ -403,9 +407,20 @@ class MainFragment : Fragment() {
...
+                            ValidationResult.TokenInvalid -> {
+                                MaterialAlertDialogBuilder(requireContext())
+                                    .setTitle(getString(R.string.oauth_expired_title))
+                                    .setMessage(getString(R.string.oauth_expired_message))
+                                    .setPositiveButton(getString(R.string.oauth_expired_login_again)) { _, _ -> navigateSafe(R.id.action_mainFragment_to_loginFragment) }
+                                    .setNegativeButton(getString(R.string.dialog_dismiss)) { _, _ -> } // default action is dismissing anyway
+                                    .create().show()
+                            }
+                            ValidationResult.Failure      -> showSnackBar(getString(R.string.oauth_verify_failed))
+                        }
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt:423]: Can you move this block up where the other flow collections are also placed?

File: app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt [hunk 10]
```diff
@@ -403,9 +407,20 @@ class MainFragment : Fragment() {
...
-                        showSnackBar(getString(R.string.snackbar_login, name))
+                    // wait for username to be validated before showing snackbar
+                    collectFlow(dankChatViewModel.oAuthResult) {
+                        when (it) {
+                            is ValidationResult.User      -> showSnackBar(getString(R.string.snackbar_login, it.username))
+                            ValidationResult.TokenInvalid -> {
+                                MaterialAlertDialogBuilder(requireContext())
+                                    .setTitle(getString(R.string.oauth_expired_title))
+                                    .setMessage(getString(R.string.oauth_expired_message))
+                                    .setPositiveButton(getString(R.string.oauth_expired_login_again)) { _, _ -> navigateSafe(R.id.action_mainFragment_to_loginFragment) }
```
Comment (flex3r) [inline app/src/main/kotlin/com/flxrs/dankchat/main/MainFragment.kt:418]: We should use the existing `openLogin()` method here. Also setting the `isRelogin` parameter to true prevents the cookies from being deleted and in the most cases the login will work without having to input credentials again.

**Review by flex3r — CHANGES_REQUESTED** [review]
Tested the PR and works fine👍
Last couple comments, I swear

**Review by flex3r — APPROVED** [review]
LGTM image
